### ISSUE TITLE
Incompatible JNA library error in start.log

### ISSUE THREAD

**Issue by rob42** [rob42/freeboard-server#11]
After upgrading to current version (19/05/2016) data from the freeboard interface board, or any device on a USB>Seral port stops arriving.
Looking in the logs/start.log shows:
```
There is an incompatible JNA native library installed on this system
/home/pi/freeboard-server/jna:/usr/java/packages/lib/arm:/lib:/usr/lib.
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

        at com.sun.jna.Native.<clinit>(Native.java:158)
        at jtermios.linux.JTermiosImpl.<clinit>(JTermiosImpl.java:58)
        at jtermios.JTermios.<clinit>(JTermios.java:317)
        at purejavacomm.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:101)
        at nz.co.fortytwo.freeboard.server.SerialPortReader.connect(SerialPortReader.java:88)
        at nz.co.fortytwo.freeboard.server.SerialPortManager.run(SerialPortManager.java:121)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by rob42** [comment]
The problem is that the JNA library has been upgraded to from 3.6 to 4.0. 
3.6 did not have a build for raspberrypi so one was put manually into freeboard-server/jna. 4.0 has the libarary already, but the earlier libarary is still on the path. 

Delete the jna directory `rm -rf jna/` and restart the server.

**Comment by ph1l** [comment]
So, LD_LIBRARY_PATH setting is no longer needed in start script, right?

https://github.com/rob42/freeboard-server/blob/master/startpc.sh#L14

**Comment by rob42** [comment]
Ah, good point. The LD_LIBRARY_PATH is no longer needed either

At the time raspberry pi (particularly ARM6) was not in the library. So I compiled and added it manually. But with RPi going to ARM7(?) its not needed any more.

Just thinking - it may still be needed for a very early RPi (A or B) - havent checked that.

Rob

May 17 2016 9:53 AM, "Philip Freeman"  wrote:
	So, LD_LIBRARY_PATH setting is no longer needed in start script, right?

	https://github.com/rob42/freeboard-server/blob/master/startpc.sh#L14 (https://github.com/rob42/freeboard-server/blob/master/startpc.sh#L14)

**Comment by ph1l** [comment]
Which Pies does the project intend the freeboard-server to support? I've been playing around with freeboard-server on a Pi1 rev2, but have a Pi3 model B on order.

**Comment by rob42** [comment]
Hasnt been an issue until the recent pi2 and pi3!. It should support all really, but given the very low cost of a better pi it would simplify things quite a bit to support only Pi2 and Pi3 forwards.
May 17 2016 10:25 AM, "Philip Freeman"  wrote:
	Which Pies does the project intend the freeboard-server to support? I've been playing around with freeboard-server on a Pi1 rev2, but have a Pi3 model B on order.
