### ISSUE TITLE
Copying across NZ map files to RPi server.

### ISSUE THREAD

**Issue by pimadness** [rob42/freeboard-server#18]
Hi,

I'm having trouble trying to copy the NZ chart files over ssh from my OS X Terminal to the RPi /maps folder. Any suggestions for what works for other Freeboard users?

I've tried via USB stick - wouldn't mount. Have tried via ssh using "scp" and rsync. After getting the destination path right there are consistent messages of no such file ...  even after dragging the directory into Terminal to get the correct originating path.

Grateful for any advice.

**Comment by ph1l** [comment]
Is this a recently installed Raspberry Pi? (did you use the [setup_raspien.sh](https://github.com/rob42/freeboard-server/blob/master/setup_raspbian.sh) script to setup your pi?)

**Comment by ph1l** [comment]
This command (from OSX) should work:

    scp mapfile.zip pi@freeboard:/home/pi/maps/

If it does not, can you include the output of the following command:

    ssh pi@freeboard ls -la /home/pi

**Comment by pimadness** [comment]
HI ph1l,

Yes I think I used setup_raspbien.sh. 
Screenshot below as requested.

![screen shot 2016-06-07 at 9 14 01 pm](https://cloud.githubusercontent.com/assets/19758043/15852518/5eddbe82-2cf5-11e6-8654-e29052ec8ed0.png)

Many thanks,

**Comment by ph1l** [comment]
you're running the scp command on the wrong machine. you should be running the scp from the mac.
-- 
.

**Comment by pimadness** [comment]
Doh!   Got it to work. Many thanks.
