### ISSUE TITLE
Chart instll

### ISSUE THREAD

**Issue by RBerliner** [rob42/freeboard-server#21]
I am now struggling with the chart install. I have not done much with this to date because so many charts in my area were skewed and did not properly convert.

I have a Pi model 2 B+ and I am running the freeboard-server commit 9893b71ccb2b2c5c795744d96c419894e15cc57f

rberliner@BigIA-Ubuntu:~/Dropbox/freeboard/freeboard-server$ git log
commit 9893b71ccb2b2c5c795744d96c419894e15cc57f
Author: RBerliner <RBerliner@InstrumentationAssociates.com>
Date:   Thu May 12 12:46:00 2016 -0400

    Clip the sparkline values so that the scaling does not get screwed up by val

I have transferred the charts over to the mapcache directory so that it appears as shown below:

rberliner@BigIA-Ubuntu:~$ ssh pi@192.168.0.1
pi@192.168.0.1's password: 
Permission denied, please try again.
pi@192.168.0.1's password: 
Linux freeboard 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Jan 28 23:35:29 2016 from 192.168.0.10
pi@freeboard ~ $ cd freeboard-server
pi@freeboard ~/freeboard-server $ cd mapcache
pi@freeboard ~/freeboard-server/mapcache $ ls -la
total 32
drwxr-xr-x  8 pi pi 4096 Jan 29 11:35 .
drwxr-xr-x 11 pi pi 4096 Jan 10 18:27 ..
drwxr-xr-x  8 pi pi 4096 Jan 28 23:32 11552_1
drwxr-xr-x  6 pi pi 4096 Jan 28 23:32 11552_2
drwxr-xr-x  6 pi pi 4096 Jan 28 23:33 11552_3
drwxr-xr-x  6 pi pi 4096 Jan 28 23:33 11552_4
drwxr-xr-x  7 pi pi 4096 Jan 10 18:22 WORLD
drwxr-xr-x  9 pi pi 4096 Jan 10 18:22 WORLD1
pi@freeboard ~/freeboard-server/mapcache $ cd 11552_1
pi@freeboard ~/freeboard-server/mapcache/11552_1 $ ls -la
total 48
drwxr-xr-x  8 pi pi 4096 Jan 28 23:32 .
drwxr-xr-x  8 pi pi 4096 Jan 29 11:35 ..
drwxr-xr-x  5 pi pi 4096 Jan 28 23:31 10
drwxr-xr-x  6 pi pi 4096 Jan 28 23:31 11
drwxr-xr-x  9 pi pi 4096 Jan 28 23:32 12
drwxr-xr-x 14 pi pi 4096 Jan 28 23:32 13
drwxr-xr-x 25 pi pi 4096 Jan 28 23:31 14
drwxr-xr-x 46 pi pi 4096 Jan 28 23:32 15
-rw-r--r--  1 pi pi  255 Jan 28 23:31 freeboard.txt
-rw-r--r--  1 pi pi 6875 Jan 28 23:31 openlayers.html
-rw-r--r--  1 pi pi  998 Jan 28 23:31 tilemapresource.xml
pi@freeboard ~/freeboard-server/mapcache/11552_1 $ 

The charts in mapcache show up in the config window:

![screenshot from 2016-06-10 11 15 34](https://cloud.githubusercontent.com/assets/3680585/15970004/871b7c92-2f00-11e6-8a06-638afffa5d3b.png)

All of this is just after reboot of the RPi. That is to say I loaded the charts in the Displayed Charts panel before reboot.

The charts do not show in the Layers window and do not show up in the chartplotter (all I see is the world charts).

What do I need to do?

**Comment by ph1l** [comment]
The process I have used is:

1. install the maps to mapcache
2. restart the freeboard-server
3. enable the maps in settings
4. (SHIFT-)reload the web interface

Then they would show up as layers.

**Comment by RBerliner** [comment]
Hello Phillip freeman:

Thank you for the suggestions.

The (SHIFT-)reload does indeed get the charts to show up in the layers
window. (what command is that?) I feel I am one step closer but I am not
out of the woods yet.

The charts still do not display and Chrome's developer tools show the
following error:

Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
http://c.192.168.0.1:8080/mapcache/11552_1/15/9379/19795.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://c.192.168.0.1:8080/mapcache/11552_1/15/9378/19796.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://c.192.168.0.1:8080/mapcache/11552_1/15/9381/19793.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://c.192.168.0.1:8080/mapcache/11552_1/15/9382/19796.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://c.192.168.0.1:8080/mapcache/11552_1/15/9376/19794.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://a.192.168.0.1:8080/mapcache/11552_1/15/9377/19795.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://a.192.168.0.1:8080/mapcache/11552_1/15/9376/19796.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://a.192.168.0.1:8080/mapcache/11552_1/15/9381/19795.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://a.192.168.0.1:8080/mapcache/11552_1/15/9382/19794.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://a.192.168.0.1:8080/mapcache/11552_1/15/9378/19794.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://a.192.168.0.1:8080/mapcache/11552_1/15/9380/19796.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://b.192.168.0.1:8080/mapcache/11552_1/15/9377/19796.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://b.192.168.0.1:8080/mapcache/11552_1/15/9381/19796.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://b.192.168.0.1:8080/mapcache/11552_1/15/9376/19793.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://b.192.168.0.1:8080/mapcache/11552_1/15/9380/19793.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://b.192.168.0.1:8080/mapcache/11552_1/15/9378/19795.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED
http://b.192.168.0.1:8080/mapcache/11552_1/15/9379/19794.png Failed to load
resource: net::ERR_NAME_RESOLUTION_FAILED

I checked: these png files are just where they are supposed to be and with
these names.

Still stuck!

Ron

On Fri, Jun 10, 2016 at 1:18 PM, Philip Freeman <notifications@github.com>
wrote:

> The process I have used is:
>
>    1. install the maps to mapcache
>    2. restart the freeboard-server
>    3. enable the maps in settings
>    4. (SHIFT-)reload the web interface
>
> Then they would show up as layers.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rob42/freeboard-server/issues/21#issuecomment-225242417>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADgpSXKV4gWsqY6ayP5DPrU1qFuaGn3Aks5qKZxxgaJpZM4IzE3W>
> .
>



-- 

R. Berliner
Instrumentation Associates
101 Echowood Ln
Cary, NC 27518

e-mail: rberliner@InstrumentationAssociates.com

www.InstrumentationAssociates.com <http://www.InstrumntationAssociates.com>

Tel     734-646-5318

**Comment by rob42** [comment]
Its probably this : http://**c.**192.168.0.1:8080/mapcache/11552_1/15/9379/19795.png 

Fo chart loading efficiency the onboard Pi Wifi pretends to be 4 servers (a.pi, b.pi,c.pi...). That only works for dns names, not IP addresses.

If you have the DNS setting in the config set to boat and you are running on the Pi's inbuilt wifi then its good. If you are running on a different WIFI router (eg like at home) then set the DNS to 'home' in the config screen, save and restart the Pi. 

It should look like: http://192.168.0.1:8080/mapcache/11552_1/15/9379/19795.png 

Easily tested, just paste the url into your browser, you should get a little map tile

**Comment by RBerliner** [comment]
Thanks Rob:

That was it.

Changing to Home and got the charts after SHIFT-Reload.

Ron


On Fri, Jun 10, 2016 at 5:52 PM, rob42 <notifications@github.com> wrote:

> Its probably this : http://*c.*
> 192.168.0.1:8080/mapcache/11552_1/15/9379/19795.png
>
> Fo chart loading efficiency the onboard Pi Wifi pretends to be 4 servers
> (a.pi, b.pi,c.pi...). That only works for dns names, not IP addresses.
>
> If you have the DNS setting in the config set to boat and you are running
> on the Pi's inbuilt wifi then its good. If you are running on a different
> WIFI router (eg like at home) then set the DNS to 'home' in the config
> screen, save and restart the Pi.
>
> It should look like:
> http://192.168.0.1:8080/mapcache/11552_1/15/9379/19795.png
>
> Easily tested, just paste the url into your browser, you should get a
> little map tile
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rob42/freeboard-server/issues/21#issuecomment-225305094>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADgpSbS-DYZmRag-KfVsZFUJBidOZiC_ks5qKdyygaJpZM4IzE3W>
> .
>



-- 

R. Berliner
Instrumentation Associates
101 Echowood Ln
Cary, NC 27518

e-mail: rberliner@InstrumentationAssociates.com

www.InstrumentationAssociates.com <http://www.InstrumntationAssociates.com>

Tel     734-646-5318
