### ISSUE TITLE
Chartplotter Issues

### ISSUE THREAD

**Issue by pimadness** [rob42/freeboard-server#34]
Hi all,
I seemed to have deleted my previous thread on this. I'm doing this at home in my doestic wifi environment but accessing the Freeboard server over it's freeboard wifi network.  I don't think I've modified any DNS settings anywhere. I HAD reached the stage of having the boat located by GPS on the default world maps. I then managed to process some charts and get them in the correct directories. Since trying to select and use from the Config -> Charts panel I have been unable to get anything to display - attempts to call up Chartplotter leads to "processing" then Error 5.

I'll attach screenshots 1-5.  Please see text below explaining what I've been trying to do.

If changes to DNS settings are required can you direct me to the instructions please.

What I've done:

Accessed Freeboard wifi 
Opened Firefox browser
Opened http://192.168.0.1:8080/freeboard/

All good - screen shot 1
Three Instruments Only pages display instruments and some dials move

Going to Chartplotter Laptop page presents a blank screen with “Processing” in middle. After a couple of minutes it presents “Error code 5: user error, server response” page. See screenshot 2.

Going to Browser Console - JS -> with Errors, Warnings, Logs all ticked gives Screenshot 3.

If I go in via Ïnstruments Only” “Sail” and select “Config” I have Screenshot 4. 

baud rate 38400, device ports to scan /dev/ttyUSB0,/dev/ttyUSB1,/dev/ttyUSB2,/dev/ttyACM0,/dev/ttyACM1,/dev/ttyACM2.

Selecting Charts I have screenshot 5.

![screen shot 1 2017-02-06](https://cloud.githubusercontent.com/assets/19758043/22628841/2ec69f92-ec40-11e6-935a-d5a3a5c7c4a7.png)
![screen shot 2 2017-02-06](https://cloud.githubusercontent.com/assets/19758043/22628838/2ec500f6-ec40-11e6-98cd-280b51ed066c.png)
![screen shot 3 2017-02-06](https://cloud.githubusercontent.com/assets/19758043/22628842/2ec6fec4-ec40-11e6-971a-f1b18632ec7f.png)
![screen shot 4 2017-02-06](https://cloud.githubusercontent.com/assets/19758043/22628840/2ec61d1a-ec40-11e6-9093-8ad4ee0ce8ba.png)
![screen shot 5 2017-02-06](https://cloud.githubusercontent.com/assets/19758043/22628839/2ec5dd82-ec40-11e6-98c5-7f38aeecf028.png)

**Comment by rob42** [comment]
The error in the browser console is 'WORLD not defined', meaning it could not find the Natural Earth chart, the first one it loads. This suggests that the mapping widget  in the browser cant connect/find the pi server using the url in the layers.js file.

In the Configuration panel try selecting 'Home' button, save, then reboot. This will affect the DNS resolution and may help.

If not, then find the layers.js file (in /home/pi/freeboard-server/freeboard/js/) and paste it in here.
You can pretty print it https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by pimadness** [comment]
Thank you, will do and report back.

**Comment by pimadness** [comment]
Rob,

the layers.js file contains:

Last login: Mon Feb  6 16:18:33 on console
matt-harwards-macbook-air-2:~ navigator$ ssh pi@192.168.0.1
pi@192.168.0.1's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Jun 11 12:52:52 2016 from mattharardsair2
pi@freeboard:~ $ ls
freeboard-server  maps_BASE_816_transfered  setup_raspbian.sh
pi@freeboard:~ $ cd freeboard-server
pi@freeboard:~/freeboard-server $ ls
CHART-INSTALL.txt  mapcache                startdev.bat
conf               maps_zipped             startdev.sh
DNS_NOTES.txt      nbactions.xml           startpc.bat
docs               NMEA.txt                startpc.sh
freeboard          pom.xml                 start.sh
install_bbb.sh     pom.xml.versionsBackup  systemd.freeboard.environment
INSTALL.txt        README_install_Pi.md    systemd.freeboard.service
LIBRARIES.txt      README.md               target
LICENCE.TXT        setup_raspbian.sh       tracks
logs               src
pi@freeboard:~/freeboard-server $ cd freeboard
pi@freeboard:~/freeboard-server/freeboard $ ls
anchorWindow.zul     floating.zul  mainToolbar.zul    WEB-INF
autopilotWindow.zul  img           META-INF           widgets
calibration.zul      index.zul     nav                wind1.zul
configWindow.zul     js            sailToolbar.zul    wind2.zul
cpToolbar.zul        LICENCE.TXT   sail.zul           windLogg.zul
depth.zul            logg1.zul     simpleToolbar.zul  wind.zul
engine.zul           logg.zul      WARRANTY.TXT
pi@freeboard:~/freeboard-server/freeboard $ cd js
pi@freeboard:~/freeboard-server/freeboard/js $ ls
anchor.js                   jquery.comet.js              leaflet-src.js
autopilot.js                jquery.cookie.js             logg.js
calibrate.js                jquery.sparkline.js          Marker.Rotate.js
chartplotter.js             jquery.sparkline.min.js      multi.js
depth.js                    layers.js                    OpenLayers.js
engine.js                   layers.js.default            org
freeboard-comet.js          L.Control.MousePosition.css  processing.js
GPX.js                      L.Control.MousePosition.js   sail.js
images                      leaflet.css                  steelseries.js
img                         leaflet.draw.css             steelseries-min.js
jquery-1.8.2.min.js         leaflet.draw.ie.css          theme
jquery-1.8.3.js             leaflet.draw.js              Tween.lib
jquery.cometd-ack.js        leaflet.draw-src.js          tween-min.js
jquery.cometd.js            leaflet.ie.css               websocket.js
jquery.cometd-reload.js     leaflet.js                   wind2.js
jquery.cometd-timestamp.js  leaflet.measure.css          wind.js
jquery.cometd-timesync.js   leaflet.measure.js           windLogg.js
pi@freeboard:~/freeboard-server/freeboard/js $ vi layers.js
```javascript
function addLayers(map) {
        var host = window.location.hostname;

        var WORLD1 = L.tileLayer("http://{server}:8080/mapcache/WORLD1/{z}/{x}/{y}.png", {
                server: host,

                attribution: 'Natural Earth 1',
                minZoom: 3,
                maxZoom: 6,
                tms: true
                }).addTo(map);


        var WORLD = L.tileLayer("http://{server}:8080/mapcache/WORLD/{z}/{x}/{y}.png", {
                server: host,

                attribution: 'Natural Earth',
                minZoom: 0,
                maxZoom: 4,
                tms: true
                }).addTo(map);


        var NZ46301 = L.tileLayer("http://{server}:8080/mapcache/NZ46301/{z}/{x}/{y}.png", {
                server: host,

                attribution: 'NZ46301 Approaches to Wellington NU/NZ46301 RA/1',
                minZoom: 9,
                maxZoom: 14,
                tms: true
                }).addTo(map);

        baseLayers = {
                "World": WORLD,
```
Cheers,

M

**Comment by rob42** [comment]
Try using nano rather than vi (unless you are a serious unix geek), its more like PC editors.
You seem to be missing the bottom section, but that may just be below the console window, it should look like:
```javascript
baseLayers = {
		"World": WORLD,
	};
	overlays = {
		"Natural Earth": WORLD,
		"Natural Earth 1": WORLD1,
		"NZ23 New Zeland North Island": NZ23,
		"NZ614 Tasman Bay": NZ614,
		"NZ61 Karamea River to Stephens Island": NZ61,
		"NZ6142_1 Nelson Harbour & Entrance": NZ6142_1,
		"NZ6142_2 Nelson Harbour & Entrance - Port Nelson": NZ6142_2,
		"NZ6144 Abel Tasman": NZ6144,
	};
	layers = L.control.layers(baseLayers, overlays).addTo(map);
	};
```
If its not there, then thats the problem. You can delete layers.js  and it will be recreated properly when you save the config again.

**Comment by pimadness** [comment]
Success!  Following your instructions got the World maps back.  Then found my Wellington chart wasn't being seen because the path was missing an intermediate directory - I'll have to move the final chart file out of the higher directory so it is a directory in /mapcache/.

So now to install a one more chart and then get it connected to kit in the boat - will want to add the IMU at some stage soon. Thanks for your prompt assistance!
